language: python
  - 3.6
  - 3.7
stages:
  - test
  - name: deploy
    if: branch = master
install:
  - pip install --upgrade pip
  - pip install .
  - pip install setuptools wheel pylint
script:
  - pylint certbot_dns_freenom
  - echo "$SECRET_KEY"
deploy:
  provider: pypi
  user: "__token__"
  password: "Your PyPI API token, including the pypi- prefix"
