language: python
  - 3.6
  - 3.7
stages:
  - test
  - name: deploy
    if: branch = master
install:
  - pip install --upgrade pip
  - pip install .
  - pip install setuptools wheel pylint
script:
  - pylint certbot_dns_freenom
deploy:
  provider: pypi
  user: "__token__"
  password: "$SECRET_TOKEN"
