language: python
  - 3.6
  - 3.7
stages:
  - install
  - test
  - name: build
    if: branch = master
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: install
      install:
        - pip install --upgrade pip
        - pip install .
        - pip install setuptools wheel
          #    - stage: test
          #      install:
          #        - pip install pylint
          #      script:
          #        - pylint certbot_dns_freenom
          #    - language: python
          #      python: 3.6
          #        - stage: build
          #          script: python3 setup.py sdist bdist_wheel
          #    - language: python
          #      python: 3.6
          #        - stage: deploy
          #          script: echo "deploy only in python 3.6"
