language: python
stages:
  - test
  - name: deploy
    if: branch = master
jobs:
  include:
    - install:
      - pip install --upgrade pip
      - pip install .
      - pip install setuptools wheel pylint
      script: pylint certbot_dns_freenom
    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: "__token__"
        password: "$SECRET_TOKEN"
      on:
        tags: true
