#!/bin/bash
set -ex

WORK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source "$WORK_DIR/lib/common"

PLUGIN_VERSION=$(GetCerbotVersionFromTag "$PLUGIN_VERSION")

for TARGET_ARCH in "${ALL_TARGET_ARCH[@]}"; do
    TagDockerImageAliases "${TARGET_ARCH}" "${PLUGIN_VERSION}"
    PushDockerImageAliases "${TARGET_ARCH}" "${PLUGIN_VERSION}"
done
