---
name: Python package
on:
  - push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-black yamllint
      - name: Lint with flake8
        run: |
          flake8 .
      - name: Lint with yamllint
        run: |
          yamllint .
  build:
    needs: lint
    steps:
      - uses: docker/build-push-action@v2
        name: Docker Build
        with:
          context: .
          tags: shm013/certbot-dns-freenom:latest
          build-args: "ARCH=amd64,CERTBOT_VERSION=1.16.0"
