---
name: Python package
on:
  - push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-black yamllint
      - name: Lint with flake8
        run: |
          flake8 .
      - name: Lint with yamllint
        run: |
          yamllint .
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: shm013/certbot-dns-freenom:latest
          load: true
          build-args: |
            ARCH=amd64
            CERTBOT_VERSION=1.16.0

      - name: Prepare test
        run: |
          mkdir letsencrypt
          echo "certbot_dns_freenom:dns_freenom_username = \
          ${{ secrets.FREENOM_USERNAME }}
          certbot_dns_freenom:dns_freenom_password = \
          ${{ secrets.FREENOM_PASSWORD }}" > credentials.ini
          chmod 600 credentials.ini

      - name: Perform test
        run: "docker run
        --pull never \
        -v ${PWD}/credentials.ini:/credentials.ini \
        -v ${PWD}/letsencrypt:/etc/letsencrypt \
        shm013/certbot-dns-freenom:latest certonly \
        -a certbot-dns-freenom:dns-freenom \
        --certbot-dns-freenom:dns-freenom-credentials /credentials.ini \
        --certbot-dns-freenom:dns-freenom-propagation-seconds 300 \
        -d '*.${{ secrets.FREENOM_DOMAIN }}' \
        -m ${{ secrets.FREENOM_USERNAME }} \
        --server https://acme-staging-v02.api.letsencrypt.org/directory \
        --agree-tos -n"
