name: Python package
on: 
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Lint with black
        run: |
          black --check .
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest black
          pip install .
      - name: Create credentials.ini
        run: |
          echo "certbot_dns_freenom:dns_freenom_username = ${{ secrets.FREENOM_USERNAME }}\n
          certbot_dns_freenom:dns_freenom_password = ${{ secrets.FREENOM_PASSWORD }}"
          > credentials.ini
      - name: Test
        run: |
          certbot certonly -a certbot-dns-freenom:dns-freenom
            --certbot-dns-freenom:dns-freenom-credentials ${PWD}/credentials.ini
            --certbot-dns-freenom:dns-freenom-propagation-seconds 300
            -d "*.certbot-dns-freenom-test.ml"
            -d certbot-dns-freenom-test.ml
            -m admin@example.com
            --server https://acme-staging-v02.api.letsencrypt.org/directory
            --agree-tos -n
