name: Python package
on: 
  - push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-black
      - name: Lint with flake8
        run: |
          flake8 .
#      - name: Install certbot_dns_freenom
#        run: |
#          pip install .
#      - name: Prepare
#        run: |
#          mkdir letsencrypt
#          echo "certbot_dns_freenom:dns_freenom_username = ${{ secrets.FREENOM_USERNAME }}\n
#          certbot_dns_freenom:dns_freenom_password = ${{ secrets.FREENOM_PASSWORD }}" > credentials.ini
#          chmod 600 credentials.ini
#      - name: Test
#        run: |
#          certbot certonly -a certbot-dns-freenom:dns-freenom \
#            --certbot-dns-freenom:dns-freenom-credentials ${PWD}/credentials.ini \
#            --certbot-dns-freenom:dns-freenom-propagation-seconds 300 \
#            -d "*.certbot-dns-freenom-test.ml" \
#            -d "certbot-dns-freenom-test.ml" \
#            -m shm0x1101@gmail.com \
#            --server https://acme-staging-v02.api.letsencrypt.org/directory \
#            --logs-dir letsencrypt \
#            --config-dir letsencrypt \
#            --work-dir letsencrypt \
#            --agree-tos -n
