---
name: ci
on:  # yamllint disable-line rule:truthy
  push:
    branches-ignore:
      - master
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-black yamllint
      - name: Lint with flake8
        run: |
          flake8 .
      - name: Lint with yamllint
        run: |
          yamllint .
