---
name: dockerhub

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: shm013/certbot-dns-freenom
          tags: |
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test
        run: |
          echo "${{ steps.meta.outputs.tags }}"
      - name: Test
        run: |
          echo "${{ steps.meta.outputs.labels }}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ARCH=amd64
            CERTBOT_VERSION=1.22.0

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
