name: release

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  test_version:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Version  
        id: version  
        uses: juliansangillo/tag-version@v1
        with:
          production-branch: master

      - name: Test
        run: echo ${{ steps.version.revision }}

      - name: Test 2
        run: echo $(python setup.py --version)
